service: tela-vermelha

provider:
  name: aws
  runtime: nodejs20.x

  stage: dev
  region: us-east-1

functions:
  register:
    # role: ${ssm:${self:custom.stage}-register-iam-role}
    name: ${self:service}-register
    handler: register/handler.register
    # environment:
    #   DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
    
    events:
     - http:
         path: auth
         method: post

  # login:
  #   # role: ${ssm:${self:custom.stage}-login-iam-role}
  #   handler: login/handler.login
  #   environment:
  #     DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
  #     JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
  #     EMAIL_GSI: ${ssm:${self:custom.stage}-email-gsi}
  #   events:
  #    - http:
  #        path: login
  #        method: post

  # authorizer:
  #   handler: authorizer/handler.authorizer
  #   environment:
  #     JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
         
custom:
  stage: ${opt:stage, self:provider.stage}